config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :stats

  resources :tasks

  resources :bugs

  resources :abouts

  resources :meeting2s

  resources :packages

  resources :meetings

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  def to_param
  "#{id}-#{meetingyear}-#{meetingmonth}-#{meetingdate}-#{title}".downcase.gsub(/\W+/, "-").gsub(/^[-]+|[-]$/,"").strip
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json

  def index
  #    @meetings = Meeting.all

    Rails.logger.info("MEETMER: meetings_controller.rb")    
    @meetings = Meeting.find(:all, :order => 'meetingdate DESC', :limit => 10) 
    @meetingsall = Meeting.find(:all, :order => 'meetingdate DESC', :conditions => {:meetingyear => Time.now.year})
    @meetingstotal = Meeting.find(:all)
    @cyear = Time.now.year
    @meetings1 = Meeting.find(:all, :conditions => {:meetingmonth => "1", :meetingyear => Time.now.year})
    @meetings2 = Meeting.find(:all, :conditions => {:meetingmonth => "2", :meetingyear => Time.now.year})
    @meetings3 = Meeting.find(:all, :conditions => {:meetingmonth => "3", :meetingyear => Time.now.year})
    @meetings4 = Meeting.find(:all, :conditions => {:meetingmonth => "4", :meetingyear => Time.now.year})
    @meetings5 = Meeting.find(:all, :conditions => {:meetingmonth => "5", :meetingyear => Time.now.year})
    @meetings6 = Meeting.find(:all, :conditions => {:meetingmonth => "6", :meetingyear => Time.now.year})
    @meetings7 = Meeting.find(:all, :conditions => {:meetingmonth => "7", :meetingyear => Time.now.year})
    @meetings8 = Meeting.find(:all, :conditions => {:meetingmonth => "8", :meetingyear => Time.now.year})
    @meetings9 = Meeting.find(:all, :conditions => {:meetingmonth => "9", :meetingyear => Time.now.year})
    @meetings10 = Meeting.find(:all, :conditions => {:meetingmonth => "10", :meetingyear => Time.now.year})
    @meetings11 = Meeting.find(:all, :conditions => {:meetingmonth => "11", :meetingyear => Time.now.year})
    @meetings12 = Meeting.find(:all, :conditions => {:meetingmonth => "12", :meetingyear => Time.now.year})

    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meetings = Meeting.find(:all, :order => 'meetingdate DESC', :limit => 10)
    @meetingsall = Meeting.find(:all, :order => 'meetingdate DESC')
    @meeting = Meeting.find(params[:id])
    @meetingstotal = Meeting.find(:all)
   
    @meetings1 = Meeting.find(:all, :conditions => {:meetingmonth => "1", :meetingyear => Time.now.year})
    @meetings2 = Meeting.find(:all, :conditions => {:meetingmonth => "2", :meetingyear => Time.now.year})
    @meetings3 = Meeting.find(:all, :conditions => {:meetingmonth => "3", :meetingyear => Time.now.year})
    @meetings4 = Meeting.find(:all, :conditions => {:meetingmonth => "4", :meetingyear => Time.now.year})
    @meetings5 = Meeting.find(:all, :conditions => {:meetingmonth => "5", :meetingyear => Time.now.year})
    @meetings6 = Meeting.find(:all, :conditions => {:meetingmonth => "6", :meetingyear => Time.now.year})
    @meetings7 = Meeting.find(:all, :conditions => {:meetingmonth => "7", :meetingyear => Time.now.year})
    @meetings8 = Meeting.find(:all, :conditions => {:meetingmonth => "8", :meetingyear => Time.now.year})
    @meetings9 = Meeting.find(:all, :conditions => {:meetingmonth => "9", :meetingyear => Time.now.year})
    @meetings10 = Meeting.find(:all, :conditions => {:meetingmonth => "10", :meetingyear => Time.now.year})
    @meetings11 = Meeting.find(:all, :conditions => {:meetingmonth => "11", :meetingyear => Time.now.year})
    @meetings12 = Meeting.find(:all, :conditions => {:meetingmonth => "12", :meetingyear => Time.now.year})


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper

  def JanCount
   puts @meetingstotal.count

  end

end

app/views/meetings/_accordion.html.haml
.container
  %h2.acc_trigger
    %a{:href=>"#"} Meetings info
  .acc_container
    .block
      %ul.accordion
        %li In #mer-meeting (irc.freenode.net)
        %li using the MeetBot
    .block
      %h3 Details
      %ul.accordion
        %li 
          Meeting count(all):
          %span.value 
            = @meetingstotal.count
        %li 
          Meeting count(this year):
          %span.value
            = @meetingsall.count
  - (1..12).each do |i|
    %h2.acc_trigger
      %a{:href=>"#"} 
        Meetings 
        = @meetings[0].meetingyear
        \/
        = i
        %span.count
          (
          - if i == 1
            = @meetings1.count
          - if i == 2
            = @meetings2.count
          - if i == 3 
            = @meetings3.count
          - if i == 4 
            = @meetings4.count
          - if i == 5 
            = @meetings5.count
          - if i == 6 
            = @meetings6.count
          - if i == 7 
            = @meetings7.count
          - if i == 8 
            = @meetings8.count
          - if i == 9 
            = @meetings9.count
          - if i == 10 
            = @meetings10.count
          - if i == 11 
            = @meetings11.count
          - if i == 12 
            = @meetings12.count
          ) 
    .acc_container
      .block
        %ul.column
          - @meetingsall.each do |item|
            - if item.meetingmonth == i.to_s
              %li
                %div.date
                  = item.meetingdate
                  %div.title
                    = link_to item.title, item

app/views/meetings/_content.html.haml
%p This is partial
 
%p 
  Title:
  = @meeting.title

app/views/meetings/_form.html.haml
= simple_form_for(@meeting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :startTime
    = f.input :endTime
    = f.input :content
    = f.input :logsurl
    = f.input :url
    = f.input :channel
    = f.input :meetingyear
    = f.input :meetingmonth
  .form-actions
    = f.button :submit

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', @meeting
\|
= link_to 'Back', meetings_path

app/views/meetings/index.html.haml
- content_for(:head) do
  %title
    :escaped 
      #MeetMer: #Mer project meetings  
    (
    = @meetingsall.length
    ) + Meeting information

#leftcolumnwrap
  #leftcolumn
    = render "accordion"
.intro
  %h2.content 
    About regular meetings
    = render 'layouts/shared/sharebuttons'
  %p Mer aims to be a FOSS, inclusive, meritocratically governed and openly developed Core optimised for HTML5/QML/JS, providing a mobile-optimised base distribution for use by device manufacturers. Mer is based upon the work from the Core section of the MeeGo project and aims to share effort and code together with the Tizen project once Tizen tools and code are publicly available.
  %p.fancy Meetings are held in #mer-meeting on irc.freenode.net, using the MeetBot
  %p
    %b Monday
    %ul
      %li 08:00 UTC - Nemo Bug Triage
      %li 12:00 UTC - Mer Bug Triage
  %p
    %b Tuesday
    %ul
      %li 11:00 UTC - (bi-weekly odd weeks, eg. wk5 onwards) Nemo Steering Group meeting
      %li 12:00 UTC - Mer Release Management meeting
  %p
    %b Thursday
    %ul
      %li 12:OO UTC - Mer QA meeting
.intro
  %h2.content 
    Recent meetings
    %span 
      = @meetings[0].created_at
     
  %p Below you'll find 10 most recent meetings - latest first. 
  %p If you want to see older meetings, see left column where you can find all meetings sorted by months.   
  %table.bordered
    %thead
      %tr
        %th Title
        %th Date
        %th Started
        %th Ended
        %th Minutes
        %th Logs
        %th Edit
        %th Delete

    - @meetings.each do |meeting|
      %tr 
        %td.title 
          = link_to meeting.title, meeting
        %td.datetime
          = meeting.meetingdate.strftime("%Y/%m/%d") 
        %td.startTime 
          = meeting.startTime
        %td.endTime
          = meeting.endTime
        %td.url
          = link_to 'Minutes', meeting.murl, {:rel => 'shadowbox;width=1000;height=600;', :title => [meeting.channel," - " , meeting.title]} 
        %td.logsurl
          = link_to 'Discussion', meeting.logsurl, {:rel => 'shadowbox;width=1000;height=600;', :title => [meeting.channel," - " , meeting.logsurl]}
        %td= link_to 'Edit', edit_meeting_path(meeting)
        %td= link_to 'Destroy', meeting, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', meetings_path

app/views/meetings/show.html.haml
- content_for(:head) do
  %title
    :escaped
      #MeetMer: #Mer meeting details: 
    = @meeting.title 
    |
    = @meeting.meetingdate
   
#leftcolumnwrap
  #leftcolumn
    = render "accordion"

%div{:class => 'intro meeting'}
  %h2.content
    = @meeting.title
    = render 'layouts/shared/sharebuttons'
  .grouptime
    .meetingdetail_date
      %span.item Date
      %span.value
        = @meeting.meetingdate
      %span.item Started
      %span.value
      = @meeting.startTime
      %span.item Ended
      %span.value
      = @meeting.endTime
      %span.item Meeting discussion
      %li
        = link_to 'Open discussion', @meeting.logsurl, {:rel => 'shadowbox;width=1000;height=600;', :title => [@meeting.channel," - " ,@meeting.title]}
      %span.item Meeting Minutes
      %li
        = link_to 'Open minutes', @meeting.murl, {:rel => 'shadowbox;width=1000;height=600;', :title => [@meeting.channel," - " ,@meeting.title]}

    .meetingdetail_channel
      %span.item Channel
      %span.value
      = @meeting.channel
      %li.btn
        %a{:href => "http://webchat.freenode.net/?channels=mer-meeting", :target => "top"} open channel in new window
      %li.btn 
        %a{:href =>'http://webchat.freenode.net/?channels=mer-meeting', :rel => 'shadowbox;width=1000;height=600;', :title => @meeting.channel} open channel in floating div
    
  /= link_to 'Edit', edit_meeting_path(@meeting)
  /\| 
  = link_to 'Back', meetings_path