config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :stats

  resources :tasks

  resources :bugs

  resources :abouts

  resources :meeting2s

  resources :packages

  resources :meetings

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.find(:all, :order => 'updated_at DESC')
    @tasksbydate = Task.find(:all, :order => 'tpriority ASC, tseverity')
    @tasksQA = Task.find(:all, :conditions => {:tproduct => "Mer QA"})
    @tasksVendorInterface = Task.find(:all, :conditions => {:tproduct => "Mer Vendor Interface"})
    @tasksPolicies = Task.find(:all, :conditions => {:tproduct => "Mer Policies and Processes"})
    @tasksMINT = Task.find(:all, :conditions => {:tproduct => "Mer Integration Tools  MINT"})
    @tasksCore = Task.find(:all, :conditions => {:tproduct => "Mer Core"})
    @taskstypes = Task.uniq.pluck(:tproduct)
    # not implemented at database level. Community has planned some kind of keyword to identify
    # low hanging fruits.[25.7.2012] 
    @tasksBananas = Task.find(:all, :conditions => {:tproduct => "Easy"})
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_accordion.html.haml
.container
  %h2.acc_trigger
    %a{:href=>"#"} Available tasks - overview
  .acc_container
    .block
      %p 
        %strong 
          Tasks are easy way to contribute, just pick one of 
          = @tasks.count
          tasks
          and get involved. 
        %br 
         
      %div{:id =>'chart_div'}
       
    :javascript
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        #{render(:partial => "chart_pie_item", :locals => {:tasks => @tasks, :types => @taskstypes})}
        ]);

        var options = {
          title: "%'s of not taken tasks by products", is3D: false, colors:['#3161b6','#0a74ac', '#6f6f6f', '#67b7fc', '#1c4867'], legend: {position: 'left', textStyle: {color: '#000', fontSize: 10}}, chartArea:{left:20,top:50,width:"100%",height:"100%"} 
        };
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    :javascript
      $(document).ready(function() {
        $('#chart_div').delay(1200).show();
      });
    .block  
      %p Easy tasks are listed under 'Low hanging fruits' (takes a few minutes)
         
      %br   
  %h2.acc_trigger
    %a{:href=>"#"} 
      Low hanging fruits
      %span.count
        (
        = @tasksBananas.count
        )
  .acc_container
    .block
      %ul.column
        - if @tasksBananas.count == 0
          %li Yay! None found
        - else
          - @tasksBananas.each do |item|
            %li
              %div.date
                = item.updated_at
                %div.title
                  = link_to item.ttitle, item
  - @taskstypes.each do |item|
    = render :partial => 'column_item', :locals => {:tasks => @tasks, :name => item}

app/views/tasks/_chart_pie_item.html.haml
['task', 'available'], 
- j = 0
- typecount = @taskstypes.count

- @taskstypes.each do |item|
  - i = 0
  - j += 1
  - line = "['"
  - line += item 
  - line += "',"
  
  - @tasks.each do |task|
    - if task.tproduct == item
      - i += 1
  - line += String(i)
  - if j < @taskstypes.count
    - line += "],"
  - else
    - line += "]" 
  = line 
  

app/views/tasks/_column_item.html.haml
%h2.acc_trigger
  %a{:href=>"#"} 
    = name
    %span.count
      (
      - i = 0
      - @tasks.each do |item|
        - if name == item.tproduct
          - i += 1 
      = i
      )
.acc_container
  .block
    %ul.column
      - @tasks.each do |item|
        - if name == item.tproduct
          %li
            %div.date
              = item.updated_at
              %div.title
                = link_to item.ttitle, item

app/views/tasks/_form.html.haml
= simple_form_for(@task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :ttitle
    = f.input :tlink
    = f.input :tauthor
    = f.input :tproduct
    = f.input :tseverity
    = f.input :tpriority
    = f.input :tstatus

  .form-actions
    = f.button :submit

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
- content_for(:head) do
  %title
    :escaped 
      #MeetMer: #Mer not taken tasks  
    (
    = @tasks[0].created_at
    )
#leftcolumnwrap
  #leftcolumn
    = render 'accordion'
.intro
  %h2.content 
    Tasks - contribute by taking tasks
    = render 'layouts/shared/sharebuttons'
  %p More about tasks .... Perhaps something about process...

.intro
  %h2.content 
    Not taken tasks - pick one
  %p
    On the left column, you'll find tasks divided into categories: 
    %ul
      %li Low hanging fruits (takes only a few minutes to do)
      - @taskstypes.each do |category|       
        %li 
          = category

  %p 
    Below you'll find all not taken tasks 
    %span
      (list updated:  
      = @tasks[0].created_at
      ) 
  %p List can be sorted by clicking column names.  
  %table{:class => 'bordered', :id=>'sortme'}
    %thead
      %tr
        %th Title
        
        %th Priority
        %th Product
    %tbody
      - @tasks.each do |task|
        %tr 
          %td.btitle 
            = link_to task.ttitle, task
          %td.bpriority
            = task.tpriority
          %td.bseverity
            = task.tproduct

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Ttitle:
  = @task.ttitle
%p
  %b Tlink:
  = @task.tlink
%p
  %b Tauthor:
  = @task.tauthor
%p
  %b Tproduct:
  = @task.tproduct
%p
  %b Tseverity:
  = @task.tseverity
%p
  %b Tpriority:
  = @task.tpriority
%p
  %b Tstatus:
  = @task.tstatus

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path