config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :stats

  resources :tasks

  resources :bugs

  resources :abouts

  resources :meeting2s

  resources :packages

  resources :meetings

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/about.rb
class About < ActiveRecord::Base

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abouts }
    end
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
    @about = About.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @about }
    end
  end

  # GET /abouts/new
  # GET /abouts/new.json
  def new
    @about = About.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @about }
    end
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(params[:about])

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render json: @about, status: :created, location: @about }
      else
        format.html { render action: "new" }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abouts/1
  # PUT /abouts/1.json
  def update
    @about = About.find(params[:id])

    respond_to do |format|
      if @about.update_attributes(params[:about])
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about = About.find(params[:id])
    @about.destroy

    respond_to do |format|
      format.html { redirect_to abouts_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_background.html.haml
.intro
  %h2.content
    MeetMer briefly
    = render "layouts/shared/sharebuttons"
  
  #meetmer_float_right
  %p.fancy-narrow
    %b #MeetMer
    is simple dashboard-ish application written with Ruby on Rails. The primary purpose of
    %b #MeetMer
    dashboard is to help
    %b
      %a{:href =>'http://merproject.org/'}#Mer
    project contributors and other stakeholders monitor their performance and activities.


  %p 
    %b #MeetMer 
    project was started in July 2012 by newbi developer (kyyberi) who was involved in MeeGo community building in Finland. 
  
  %p MeeGo was killed early 2011 and buried (some say it was converted to Tizen), but community had started to go own way even before that and 'returned' to Mer -project. Now companies such as JollaMobile are building their products on Mer core. 
  %p Community lacked dashboard and kyyberi took the challenge in July 2012 and continues as lead developer with the help of community.   

app/views/abouts/_form.html.haml
= simple_form_for(@about) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content

  .form-actions
    = f.button :submit

app/views/abouts/_functionality.html.haml
.intro
  %h2.content
    MeetMer Functionality & Features
  %ul
    %li Lists community meetings (by months and 10 latest)
    %li You can read from each meeting: meeting minutes and complite discussion. 
    %li Lists Mer core packages. We have implemented filter to the listing to enable faster package search. 
    %li Browse bugs (including comments)
    %li Browse QA reports
    %li Browse releases
  %h3 Stores metadata
  %p MeetMer stores metadata from several sources and retrieves actual content at on request. On request refers to for example situations where user wants to read content of meeting minute file.  
  %h3 More features?  
  %p More features are implemented all the time and contributions are always welcome. 
  

app/views/abouts/_github.html.haml
.intro
  %h2.content
    MeetMer is open source
  %p Code is in Github. Clone, develop and contribute!
  %p 
    %a{:href=> 'https://github.com/kyyberi/Meet-Mer/'}https://github.com/kyyberi/Meet-Mer/
  %h3 Missing native UX? - contribute by translating
  %p 
    Internationalization and localization are managed at
    %a{:href=> 'https://www.transifex.com/projects/p/meetmer/'}Transifex

app/views/abouts/_purpose.html.haml
.intro
  %h2.content
    MeetMer Purpose - support Mer development
  #mer_float_right
  %p
    %b #MeetMer
    is simple dashboard-ish application written with Ruby on Rails. The primary purpose of
    %b #MeetMer
    dashboard is to help
    %b 
      %a{:href =>'http://merproject.org/'}#Mer
    project contributors and other stakeholders monitor their performance and activities.


  %p.fancy-narrow 
    What 
    %b 
      %a{:href =>'http://merproject.org/'}#Mer project 
    is trying to establish is a common, streamlined Linux/Qt core for others to build on top of. For end users, this is horribly boring - the code on it's own would just show a blinking cursor/a xterm/a qml demo

  %p A vendor, in our view, is someone who takes the core, mixes it with their own bits, makes it into some kind of a product. As an example this could be Plasma Active user experience, taking the core, some hardware adaptations and their own UX. It could be a small business that makes bus displays. It could be a hobbyist at home who doesn't want to bother making his own distribution and just want to show a clock on his LCD. 
  %p But we're not the people who deliver the final experience.
  %p 
    %b Mer project has clear goals:
    %ul
      %li Openly developed with transparency built into the fabric of the project
      %li Provide a mobile device oriented architecture
      %li Primary customers are device vendors - not end-users.
      %li Have structure, processes and tools to make life easy for device manufacturers
      %li Support innovation in the mobile OS space
      %li Inclusive of projects and technologies (eg MeeGo/Tizen/Qt/EFL/HTML5)
      %li Governed as a meritocracy
      %li Run as a non profit through donations

app/views/abouts/edit.html.haml
%h1 Editing about

= render 'form'

= link_to 'Show', @about
\|
= link_to 'Back', abouts_path

app/views/abouts/index.html.haml
- content_for(:head) do
  %title
    :escaped
      #MeetMer: #Mer Dashboard - Briefly, Purpose, Features and Functionality

#leftcolumnwrap
  #leftcolumn
    .container
      %h2.acc_trigger
        %a{:href=>"#"} #MeetMer Tweets
    %div{:class => 'acc_container_tweets'}
      .block_tweets
        #tweets
          %p{:id =>'tweetinit'} If you enable Javascript, tweets will appear here.


= render "background"
= render "purpose"
= render "functionality"
= render "github"

app/views/abouts/new.html.haml
%h1 New about

= render 'form'

= link_to 'Back', abouts_path

app/views/abouts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @about.title
%p
  %b Content:
  = @about.content

= link_to 'Edit', edit_about_path(@about)
\|
= link_to 'Back', abouts_path