config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :stats

  resources :tasks

  resources :bugs

  resources :abouts

  resources :meeting2s

  resources :packages

  resources :meetings

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stats }
    end
  end

  # GET /stats/1
  # GET /stats/1.json
  def show
    @stat = Stat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stat }
    end
  end

  # GET /stats/new
  # GET /stats/new.json
  def new
    @stat = Stat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stat }
    end
  end

  # GET /stats/1/edit
  def edit
    @stat = Stat.find(params[:id])
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(params[:stat])

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render json: @stat, status: :created, location: @stat }
      else
        format.html { render action: "new" }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stats/1
  # PUT /stats/1.json
  def update
    @stat = Stat.find(params[:id])

    respond_to do |format|
      if @stat.update_attributes(params[:stat])
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat = Stat.find(params[:id])
    @stat.destroy

    respond_to do |format|
      format.html { redirect_to stats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.haml
= simple_form_for(@stat) do |f|
  = f.error_notification

  .form-inputs
    = f.input :stype
    = f.input :sproduct
    = f.input :sseverity
    = f.input :scount
    = f.input :spriority
    = f.input :syear
    = f.input :smonth
    = f.input :sday

  .form-actions
    = f.button :submit

app/views/stats/edit.html.haml
%h1 Editing stat

= render 'form'

= link_to 'Show', @stat
\|
= link_to 'Back', stats_path

app/views/stats/index.html.haml
%h1 Listing stats

%table
  %tr
    %th Stype
    %th Sproduct
    %th Sseverity
    %th Scount
    %th Spriority
    %th Syear
    %th Smonth
    %th Sday
    %th
    %th
    %th

  - @stats.each do |stat|
    %tr
      %td= stat.stype
      %td= stat.sproduct
      %td= stat.sseverity
      %td= stat.scount
      %td= stat.spriority
      %td= stat.syear
      %td= stat.smonth
      %td= stat.sday
      %td= link_to 'Show', stat
      %td= link_to 'Edit', edit_stat_path(stat)
      %td= link_to 'Destroy', stat, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Stat', new_stat_path

app/views/stats/new.html.haml
%h1 New stat

= render 'form'

= link_to 'Back', stats_path

app/views/stats/show.html.haml
%p#notice= notice

%p
  %b Stype:
  = @stat.stype
%p
  %b Sproduct:
  = @stat.sproduct
%p
  %b Sseverity:
  = @stat.sseverity
%p
  %b Scount:
  = @stat.scount
%p
  %b Spriority:
  = @stat.spriority
%p
  %b Syear:
  = @stat.syear
%p
  %b Smonth:
  = @stat.smonth
%p
  %b Sday:
  = @stat.sday

= link_to 'Edit', edit_stat_path(@stat)
\|
= link_to 'Back', stats_path